<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $view \SebTech\Blog\ViewModel\BlogPostsIndex */
$view = $block->getData('blogPostsIndex');
?>

<?php
/** @var \SebTech\Blog\Model\BlogPost $blog */
foreach ($view->getAllBlogs() as $blog) { ?>
    <?php if($blog->getEnabled() === true) { ?>
    <h1><?= $blog->getTitle() ?></h1>
    <p><?php echo $view->filterContentForFrontend( $blog->getContent()); ?></p>
    <small><?= $blog->getAuthor() ?> - <?= $blog->getCreatedAt()->format("Y-m-d") ?></small>
    <hr>
        <?php } ?>
<?php } ?>
